DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    PAGE_COUNT NUMBER NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY,
    NICKNAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY,
    GENRE VARCHAR(255) NOT NULL
);
